import React, { useEffect } from 'react';
import './CodeCard.css'
import SyntaxHighlighter from 'react-syntax-highlighter';
import { agate } from 'react-syntax-highlighter/dist/esm/styles/hljs';
var TurndownService = require('turndown').default

var turndownService = new TurndownService()

interface Props {
    explanation: string;
    code: string;
    id: string;
    onChildClick: (id: string) => void;
}

const CodeCard: React.FC<Props> = ({ explanation, code, id, onChildClick }: Props) => {

    function handleClick(event: any) {
        // console.log(onChildClick)
        onChildClick(id);
    }

    function share() {
        var markdown = turndownService.turndown(explanation)
        window.open(`https://carbon.now.sh/?l=javascript&code=${encodeURIComponent('/*\n' + markdown + '\n\n- generated by [Stenography](https://www.stenography.dev/) 🤖 \n*/\n' + code)}`)
    }


    const spanRef = React.useRef<HTMLSpanElement>(null);

    useEffect(() => {
        if (spanRef.current) {
            spanRef.current.innerHTML = explanation;
        }
    }, [spanRef.current, explanation]);

    return (<div className="card" id={id}>
        <div className="code">
            <SyntaxHighlighter language="javascript" style={agate}
                wrapLongLines={true}
            >
                {code}
            </SyntaxHighlighter>
        </div>
        <div className="explanation">
            <span ref={spanRef} />
            <button className="delete" onClick={handleClick}>x</button>
            <button className="sahare" onClick={share}>share</button>
        </div>
    </div>);
}

export default CodeCard;

