import { printLine } from './modules/print';

var TurndownService = require('turndown').default

var turndownService = new TurndownService()


// TODO: only log on dev mode

var pageX;
var pageY;

document.onmousemove = function (e) {
    var x = e.pageX;
    var y = e.pageY;
    pageX = x;
    pageY = y;
};

const showModal = (pageX, pageY, data, code) => {
    const modal = document.createElement("dialog");
    if (typeof data === 'object' && data !== null && !Array.isArray(data)) data = JSON.stringify(data, null, 2);
    modal.setAttribute(
        "style", `
            width: fit-content(20em);
            left: calc(0%);
            z-index: 100;
            display: flex;
            font-family: 'Roboto', sans-serif;
            flex-direction: column;
            align-items: center;
            background-color: #fff;
            color: #000;
            border-radius: 10px;
            text-align: center;
        `
    );
    modal.innerHTML = `<div>
            <button style="width: 30px;
                font-size: 20px;
                color: #c0c5cb;
                align-self: flex-end;
                float: right;
                background-color: transparent;
                border: none;
                margin-bottom: 10px;">
                ✖</button>
            <p>${data}</p>
            <button className="sahare" id="share-btn">share</button>
    </div>`;

    document.body.appendChild(modal);
    const dialog = document.querySelector("dialog");
    dialog.showModal();
    const errorPage = document.querySelector("#apikey-options");
    if (errorPage) {
        errorPage.addEventListener("click", () => {
            chrome.runtime.sendMessage({ "open-options": "open-options-val" }, function (response) {
                // console.log(response);
            });
        });
    }
    window.onclick = function (event) {
        dialog.close();
        document.body.removeChild(modal);
    }

    dialog.querySelector("button").addEventListener("click", () => {
        dialog.close();
        document.body.removeChild(modal);
    });

    function share() {
        var markdown = turndownService.turndown(data)
        window.open(`https://carbon.now.sh/?l=javascript&code=${encodeURIComponent('/*\n' + markdown + '\n\n- generated by [Stenography](https://www.stenography.dev/) 🤖 \n*/\n' + code)}`)
        dialog.close();
        document.body.removeChild(modal);
    }

    dialog.querySelector("#share-btn").addEventListener("click", share);

}

function uuid() {
    return Date.now().toString(36) + Math.random().toString(36).substring(2);
}

chrome.runtime.onMessage.addListener(
    function (request, sender, sendResponse) {
        showModal(pageX, pageY, request.data, request.code)

        chrome.runtime.sendMessage({ "modal-shown": "modal-shown-value" }, function (response) {
            // console.log(response);
        });

        const initExplanations = []

        chrome.storage.local.get("explanations", function (result) {
            if (result["explanations"] === undefined) {
                initExplanations.push({
                    explanation: request.data.trim(),
                    code: request.code.trim(),
                    metadata: {
                        id: uuid(),
                    }
                })
                chrome.storage.local.set({ "explanations": initExplanations }, function () { });
            } else {
                const explanations = result["explanations"];
                explanations.push({
                    explanation: request.data.trim(),
                    code: request.code.trim(),
                    metadata: {
                        id: uuid(),
                    }
                })
                chrome.storage.local.set({ "explanations": explanations }, function () { });
            }
        });

    }
);

printLine("Using the 'printLine' function from the Print Module");